apiVersion: v1
kind: ConfigMap
metadata:
  name: kserve-models-web-app-config
  namespace: kserve
data:
  APP_DISABLE_AUTH: "True"
  APP_PREFIX: "/"
  APP_SECURE_COOKIES: "False"
  GRAFANA_PREFIX: "/grafana"
  GRAFANA_CPU_MEMORY_DB: "db/knative-serving-revision-cpu-and-memory-usage"
  GRAFANA_HTTP_REQUESTS_DB: "db/knative-serving-revision-http-requests"
  ALLOWED_NAMESPACES: {{ .Values.allowedNamespaces }}
