name: Terraform CI/CD

run-name: |
  Terraform CI/CD - ${{
    github.event_name == 'push' && format('main validation - {0}', github.sha) ||
    github.event_name == 'pull_request' && format('PR validation #{0} - {1}', github.event.pull_request.number, github.sha) ||
    github.event_name == 'workflow_dispatch' && format('real run - {0} - {1}', github.event.inputs.environment, github.sha) ||
    'validation'
  }}

on:
  pull_request:
    branches:
      - main
    paths:
      - src/terraform/**/*
      - .github/workflows/terraform.yml
  push:
    branches:
      - main
    paths:
      - src/terraform/**/*
      - .github/workflows/terraform.yml
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: choice
        options:
          - stalpeni
      destroy:
        description: "Check this to DESTROY resources"
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write
  issues: write
  security-events: write
  actions: read

concurrency:
  group: terraform-${{ github.event.inputs.environment || github.run_id }}
  cancel-in-progress: false

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_VERSION: 1.14.3
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/src/terraform/.terraform.d/plugin-cache
  ENV: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'pr' }}
  BACKEND_TYPE: ${{ github.event_name == 'workflow_dispatch' && 'cloud' || 'local' }}

jobs:
  scan:
    name: Security Scan (Trivy)
    runs-on: ubuntu-latest
    environment: pr
    steps:
      - uses: actions/checkout@v6

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - uses: hashicorp/setup-terraform@v3
        name: Setup Terraform
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ''

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Cache Terraform Plugins
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.TF_PLUGIN_CACHE_DIR }}
            src/terraform/.terraform
          key: terraform-${{ runner.os }}-local-${{ hashFiles('src/terraform/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-local-

      - name: Create Plugin Cache Dir
        run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: Terraform init
        working-directory: src/terraform
        run: |
          terraform init

      - name: Run Trivy TF scan
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: 'config'
          scan-ref: 'src/terraform'
          format: 'sarif'
          tf-vars: src/terraform/pr.tfvars
          output: 'trivy-terraform-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'

      - name: Upload Terraform Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        continue-on-error: true
        if: always()
        with:
          sarif_file: 'trivy-terraform-results.sarif'
          category: 'terraform'

      - name: Terraform plan
        working-directory: src/terraform
        run: |
          terraform plan -var-file=pr.tfvars -input=false -out=tfplan
          terraform show -json tfplan > tfplan.json

      - name: Prepare chart
        working-directory: src/terraform
        run: |
          node scripts/prepare_for_scan.mjs tfplan.json

      - name: Cache Helm Dependencies
        uses: actions/cache@v5
        with:
          path: src/chart/charts
          key: helm-deps-${{ hashFiles('src/chart/Chart.yaml') }}
          restore-keys: |
            helm-deps-
          
      - name: Helm dependency update
        working-directory: src/chart
        run: |
          helm dependency update
          
      - name: Run Trivy scan on Helm chart
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: 'config'
          scan-ref: 'src/chart'
          skip-setup-trivy: true
          format: 'sarif'
          output: 'trivy-helm-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'
      
      - name: Upload Helm Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        continue-on-error: true
        if: always()
        with:
          sarif_file: 'trivy-helm-results.sarif'
          category: 'helm'

      - name: Upload SARIF files as artifacts
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: trivy-sarif-results
          path: |
            trivy-terraform-results.sarif
            trivy-helm-results.sarif
          retention-days: 30


  plan:
    name: Terraform Plan / Validate
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'pr' }}
    steps:
      - uses: actions/checkout@v6

      - uses: hashicorp/setup-terraform@v3
        name: Setup Terraform
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ github.event_name == 'workflow_dispatch' && secrets.TF_TOKEN || '' }}

      - name: Create Backend Override
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: |
          cat <<EOF > ./src/terraform/backend_override.tf
          terraform {
            cloud {
              organization = "${{ secrets.TF_ORG }}"
              workspaces {
                name = "${{ env.ENV }}"
              }
            }
          }
          EOF

      - name: Cache Terraform Plugins
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.TF_PLUGIN_CACHE_DIR }}
            src/terraform/.terraform
          key: terraform-${{ runner.os }}-${{ env.BACKEND_TYPE }}-${{ hashFiles('src/terraform/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-${{ env.BACKEND_TYPE }}-

      - name: Create Plugin Cache Dir
        run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: Terraform init
        working-directory: src/terraform
        run: |
          terraform init

      - name: Terraform check fmt
        working-directory: src/terraform
        run: terraform fmt -check -recursive

      - name: Terraform validate
        working-directory: src/terraform
        run: terraform validate

      - name: Substitute Secrets
        uses: faradaytrs/substitute-secrets-action@2.7
        with:
          input: "src/terraform/${{ env.ENV }}.tfvars"
          substitutionRegex: \#\{([A-Z0-9_]+)\}
          substitutionData: ${{ toJSON(secrets) }}
          throwOnDataMissing: false

      - name: Terraform plan
        id: plan
        working-directory: src/terraform
        continue-on-error: true
        run: |
          # 1. Determine flags
          DESTROY_FLAG=""
          if [ "${{ github.event.inputs.destroy }}" == "true" ]; then
            DESTROY_FLAG="-destroy"
          fi

          # 2. Run the plan
          terraform plan $DESTROY_FLAG -input=false -var-file=${{ env.ENV }}.tfvars -out=tfplan

          # 3. Generate the summary
          echo "### Terraform Plan Summary (Env: ${{ env.ENV }})" >> $GITHUB_STEP_SUMMARY
          echo '```hcl' >> $GITHUB_STEP_SUMMARY
          terraform show -no-color tfplan >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Update PR Comment
        uses: actions/github-script@v8
        if: github.event_name == 'pull_request'
        env:
          PLAN_OUTCOME: ${{ steps.plan.outcome }}
          PLAN_STDOUT: ${{ steps.plan.outputs.stdout }}
          PUSHER: ${{ github.actor }}
          EVENT_NAME: ${{ github.event_name }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Access variables via process.env
            const { PLAN_OUTCOME, PLAN_STDOUT, PUSHER, EVENT_NAME } = process.env;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes('Terraform Plan')
            );

            const output = `#### Terraform Plan ðŸ“– \`${PLAN_OUTCOME}\`

            <details><summary>Show Plan</summary>

            \`\`\`hcl
            ${PLAN_STDOUT}
            \`\`\`

            </details>

            *Pusher: @${PUSHER}, Action: \`${EVENT_NAME}\`*`;

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            }

      - name: Check Plan Status
        if: steps.plan.outcome == 'failure'
        run: |
          echo "Terraform plan failed. Check the PR comment or logs for details."
          exit 1

      - name: Upload plan artifact
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v6
        with:
          name: tfplan
          path: src/terraform/tfplan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest

    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'

    environment: approval

    steps:
      - uses: actions/checkout@v6

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

      - name: Download plan artifact
        uses: actions/download-artifact@v7
        with:
          name: tfplan
          path: src/terraform

      - name: Create Backend Override
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: |
          cat <<EOF > ./src/terraform/backend_override.tf
          terraform {
            cloud {
              organization = "${{ secrets.TF_ORG }}"
              workspaces {
                name = "${{ env.ENV }}"
              }
            }
          }
          EOF

      - name: Cache Terraform Plugins
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.TF_PLUGIN_CACHE_DIR }}
            src/terraform/.terraform
          key: terraform-${{ runner.os }}-${{ env.BACKEND_TYPE }}-${{ hashFiles('src/terraform/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-${{ env.BACKEND_TYPE }}-

      - name: Create Plugin Cache Dir
        run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: Terraform init
        working-directory: src/terraform
        run: |
          terraform init

      - name: Terraform apply
        working-directory: src/terraform
        run: terraform apply -auto-approve tfplan
