name: Terraform

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: choice
        options:
          - stalpeni

permissions:
  contents: read

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_VERSION: 1.14.3
  TF_ORG: ${{ secrets.TF_ORG }}
  TF_WORKSPACE: ${{ github.event.inputs.environment }}

jobs:
  plan:
    name: Terraform Plan / Validate
    runs-on: ubuntu-latest

    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || null }}

    outputs:
      target_env: ${{ steps.export-env.outputs.target_env }}

    steps:
      - name: Export target environment
        id: export-env
        run: |
          echo "target_env=${{ github.event.inputs.environment }}" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ github.event_name == 'workflow_dispatch' && secrets.TF_TOKEN || '' }}

      - name: Create Backend Override
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: |
          cat <<EOF > backend_override.tf
          terraform {
            backend "remote" {
              organization = "${{ env.TF_ORG }}"
              workspaces {
                name = "${{ env.TF_WORKSPACE }}"
              }
            }
          }
          EOF

      - name: Terraform init
        run: |
          terraform init

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate

      - name: Substitute Secrets
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        uses: faradaytrs/substitute-secrets-action@2.6
        with:
          input: "${{ github.event.inputs.environment }}.tfvars"
          substitutionRegex: \#\{([A-Z0-9_]+)\}
          substitutionData: ${{ toJSON(secrets) }}
          throwOnDataMissing: false

      - name: Terraform plan
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: terraform plan -input=false -var-file=${{ github.event.inputs.environment }}.tfvars -out=tfplan

      - name: Upload plan artifact
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest

    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'

    environment: approval

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Create Backend Override
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: |
          cat <<EOF > backend_override.tf
          terraform {
            backend "remote" {
              organization = "${{ env.TF_ORG }}"
              workspaces {
                name = "${{ env.TF_WORKSPACE }}"
              }
            }
          }
          EOF

      - name: Terraform init
        run: |
          terraform init

      - name: Terraform apply (same plan)
        run: terraform apply -auto-approve tfplan
